export const MEALTYPE_ADD_REQUEST= 'MEALTYPE_ADD_REQUEST'
export const MEALTYPE_ADD_SUCCESS = 'MEALTYPE_ADD_SUCCESS'
export const MEALTYPE_ADD_FAIL = 'MEALTYPE_ADD_FAIL'

export const MEALTYPE_LIST_REQUEST= 'MEALTYPE_LIST_REQUEST'
export const MEALTYPE_LIST_SUCCESS = 'MEALTYPE_LIST_SUCCESS'
export const MEALTYPE_LIST_FAIL = 'MEALTYPE_LIST_FAIL'

export const MEALTYPE_DELETE_REQUEST = 'MEALTYPE_DELETE_REQUEST'
export const MEALTYPE_DELETE_SUCCESS = 'MEALTYPE_DELETE_SUCCESS'
export const MEALTYPE_DELETE_FAIL = 'MEALTYPE_DELETE_FAIL'

export const MEALTYPE_DETAILS_REQUEST = 'MEALTYPE_DETAILS_REQUEST'
export const MEALTYPE_DETAILS_SUCCESS = 'MEALTYPE_DETAILS_SUCCESS'
export const MEALTYPE_DETAILS_FAIL = 'MEALTYPE_DETAILS_FAIL'

export const MEALTYPE_UPDATE_REQUEST = 'MEALTYPE_UPDATE_REQUEST'
export const MEALTYPE_UPDATE_SUCCESS = 'MEALTYPE_UPDATE_SUCCESS'
export const MEALTYPE_UPDATE_FAIL = 'MEALTYPE_UPDATE_FAIL'
export const MEALTYPE_UPDATE_RESET = 'MEALTYPE_UPDATE_RESET'